### PR TITLE
Design enhancement , Bugs Fix , General fixes

### LINKED ISSUE #34: Update Design & Fix Bugs

### PR DESCRIPTION
**Pull request by ichala**
In This Pr We Updated the design , fixed some bugs, and prepared the app to be deployed

closes https://github.com/ichala/short-let-frontend/issues/34

### CODE REVIEW

File: src/Pages/Home/Home.jsx [hunk 1]
```diff
@@ -1,48 +1,15 @@
...
+import './home.css';
 
 function Home() {
-  const [Halls, setHalls] = useState(null);
-  const [Error, setError] = useState(null);
-
-  useEffect(() => {
-    GetHalls(setError, setHalls);
-  }, []);
-
```
Comment (LYANGEND) [inline src/Pages/Home/Home.jsx:14]: Good job enhancing the homepage it looks beautiful but it is static, it would be a good idea to make it more responsive for a better user experience.

**Review by LYANGEND — COMMENTED** [review]
### **Hi @ichala ,** 

### **Good job so far!**
There are some issues that I feel should be addressed before we close this pull request!

## **Highlights**
 - Linters are green 👌.
 - PR is nice 👌.

## Required Changes ♻️
_Check the comments above the review_

**Review by d2ndjim — APPROVED** [review]
@ichala , Great Job
### APPROVED ✔️ ✔️ ✔️

**Review by aimalamiri — APPROVED** [review]
Hi

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

ApprovedDavieGIF


## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Review by LYANGEND — APPROVED** [review]
APPROVED ✔️ 
Hey team good job updating the changes 👍 , the task is complete and ready to merge

**Review by EidHachem — APPROVED** [review]
